Finish reserve_app
Goto-star/reserve_app pull request #1
Opened 2022-10-07 07:47 UTC by Goto-star

rails 課題２

2022-10-07 08:08 UTC, YamanakaSayaka commented
動作を確認したところ、以下のエラーが発生しました。修正して再度提出お願いします。
・部屋を複数登録して、それぞれ予約しようとするとエラーとなります。
<img width="910" alt="スクリーンショット 2022-10-07 17 00 27" src="https://user-images.githubusercontent.com/79829190/194504687-e73ff566-cd62-448e-abc5-43ba8ab9c4d0.png">

・予約時に日付や人数を空白で登録しようとするとエラーとなります。
・エリア検索とキーワード検索の部分が隠れてしまっているようです。ご自身の環境で表示されているかを今一度ご確認ください。
<img width="1478" alt="スクリーンショット 2022-10-07 17 07 34" src="https://user-images.githubusercontent.com/79829190/194504806-47f4a24e-3fa1-41a6-98c9-6cab6837ab44.png">


※動作で不正があったため、PRへのコメントはまだいれておりません。

2022-10-08 09:14 UTC, TakuyaChida requested changes
課題のご提出ありがとうございます！
内容を確認いたしました。

部屋予約中にエラーとなってしまいましたので、
インラインコメントを確認し、対応をお願いいたします！
正常に登録ができるようになりましたら、再度PRから課題の提出をお願いいたします！

また、部屋登録の際に使用した画像がgitの差分に含まれてしまっており、gitのコミット対象となってしまっているので、この場合の対処方法としましてはgitignoreファイルに差分対象除外の設定を入れておきましょう。
対象はpublic/uploads配下のものを除外すると良いと思います。

以上、ご確認いただき再度提出をお願いいたします！

2022-10-08 09:14 UTC, TakuyaChida commented on app/controllers/rooms_controller.rb
> +        if @room.save
部屋登録ができていますね。
素晴らしいです

こちらで入力値のバリデーションが設定できると尚よいです。
現在は金額がマイナスの値でも登録できてしまっているので、データの不具合を未然に防ぐためにも登録、編集時には必須でバリデーションが設定できるようにしましょう。

rails バリデーション
などで調べるとリファレンスが乗っていますので役に立つと思います！
よろしくお願いいたします！

2022-10-08 09:14 UTC, TakuyaChida commented on app/controllers/rooms_controller.rb
> +        params.require(:room).permit(:name, :introduction, :price, :address, :image).merge(user_id: current_user.id)
パラメータが設定できていますね。
素晴らしいです！

2022-10-08 09:14 UTC, TakuyaChida commented on app/controllers/reservations_controller.rb
> +        @user = User.find(params[:id])
部屋予約の際に不具合が起こりました。

ログイン中のユーザID = 1
被予約ルームID = 3

こちらでIDが3のユーザをセレクトしてしまい不具合が起こっています。

![スクリーンショット 2022-10-08 18 08 12](https://user-images.githubusercontent.com/74874584/194699732-a3206383-4b70-468f-8dce-60445dfbe46f.png)

こちらの不具合の修正を行いましょう！
room_id = user_idの部屋以外で予約を行おうとすると画像のようなエラーとなりますので
正常に登録できていないようです。

2022-10-09 06:22 UTC, kawasaki-shohei approved these changes
前回の指摘点が修正されております。 LGTMです！
お疲れ様でした^^

2023-01-14 06:26 UTC, merged